In [1]:
from modeling_fin import *
from modeling_global import *

<html lang="ko">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   네이버 금융
  </title>
  <link href="/css/newstock.css?20190404142529" rel="stylesheet" type="text/css"/>
  <link href="/css/common.css?20190404142529" rel="stylesheet" type="text/css"/>
  <link href="/css/layout.css?20190404142529" rel="stylesheet" type="text/css"/>
  <link href="/css/main.css?20190404142529" rel="stylesheet" type="text/css"/>
  <link href="/css/newstock2.css?20190404142529" rel="stylesheet" type="text/css"/>
  <link href="/css/newstock3.css?20190404142529" rel="stylesheet" type="text/css"/>
  <link href="/css/world.css?20190404142529" rel="stylesheet" type="text/css"/>
 </head>
 <body>
  <script src="/js/jindo.min.ns.1.5.3.euckr.js?20190404142529" type="text/javascript">
  </script>
  <script src="/js/lcslog.js?20190404142529" type="text/javascript">
  </script>
  <!-- 일별시세 -->
  <div class="box_type_m">
   <h4 class="top_tlt" style="text-align:left;">
    <em>
     일별
    </em>
    시세
   </h4>
   <table cellpadding="0" cellspacing="0" class="type_1" summary="일별 시세표:날짜에 따른 체결가 전일비 등락률 거래량 거래대금 정보를 제공합니다.">
    <caption>
     일별시세
    </caption>
    <col width="15%"/>
    <col width="14%"/>
    <col width="18%"/>
    <col width="14%"/>
    <col width="*"/>
    <col width="18%"/>
    <tr>
     <th>
      날짜
     </th>
     <th>
      체결가
     </th>
     <th>
      전일비
     </th>
     <th>
      등락률
     </th>
     <th>
      거래량
      <span class="add_txt">
       (천주)
      </span>
     </th>
     <th>
      거래대금
      <span class="add_txt">
       (백만)
      </span>
     </th>
    </tr>
    <tr>
     <td class="blank_07" colspan="6">
     </td>
    </tr>
    <tr>
     <td class="date">
      2019.04.04
     </td>
     <td class="number_1">
      286.15
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       0.50
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +0.18%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      71,774
     </td>
     <td class="number_1" style="padding-right:30px;">
      3,490,961
     </td>
    </tr>
    <tr>
     <td class="date">
      2019.04.03
     </td>
     <td class="number_1">
      285.65
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       3.93
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +1.40%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      86,724
     </td>
     <td class="number_1" style="padding-right:30px;">
      3,954,146
     </td>
    </tr>
    <tr>
     <td class="date">
      2019.04.02
     </td>
     <td class="number_1">
      281.72
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       1.40
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +0.50%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      69,216
     </td>
     <td class="number_1" style="padding-right:30px;">
      3,090,863
     </td>
    </tr>
    <tr>
     <td class="blank_08" colspan="6">
     </td>
    </tr>
    <tr>
     <td class="division_line" colspan="6">
     </td>
    </tr>
    <tr>
     <td class="blank_08" colspan="6">
     </td>
    </tr>
    <tr>
    </tr>
    <tr>
     <td class="date">
      2019.04.01
     </td>
     <td class="number_1">
      280.32
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       3.84
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +1.39%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      74,689
     </td>
     <td class="number_1" style="padding-right:30px;">
      3,167,361
     </td>
    </tr>
    <tr>
     <td class="date">
      2019.03.29
     </td>
     <td class="number_1">
      276.48
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="상승" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_up.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 red02">
       1.40
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 red01">
       +0.51%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      78,160
     </td>
     <td class="number_1" style="padding-right:30px;">
      3,619,816
     </td>
    </tr>
    <tr>
     <td class="date">
      2019.03.28
     </td>
     <td class="number_1">
      275.08
     </td>
     <td class="rate_down" style="padding-right:35px;">
      <img alt="하락" height="6" src="https://ssl.pstatic.net/imgstock/images/images4/ico_down.gif" style="margin-right:4px;" width="7"/>
      <span class="tah p11 nv01">
       2.20
      </span>
     </td>
     <td class="number_1">
      <span class="tah p11 nv01">
       -0.79%
      </span>
     </td>
     <td class="number_1" style="padding-right:40px;">
      66,042
     </td>
     <td class="number_1" style="padding-right:30px;">
      2,906,687
     </td>
    </tr>
    <tr>
     <td class="blank_09" colspan="6">
     </td>
    </tr>
    <tr>
     <td class="division_line" colspan="6">
     </td>
    </tr>
   </table>
   <!--- 페이지 네비게이션 시작--->
   <table align="center" class="Nnavi" summary="페이지 네비게이션 리스트">
    <caption>
     페이지 네비게이션
    </caption>
    <tr>
     <td class="on">
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=1">
       1
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=2">
       2
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=3">
       3
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=4">
       4
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=5">
       5
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=6">
       6
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=7">
       7
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=8">
       8
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=9">
       9
      </a>
     </td>
     <td>
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=10">
       10
      </a>
     </td>
     <td class="pgR">
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=11">
       다음
       <img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarR.gif" width="3"/>
      </a>
     </td>
     <td class="pgRR">
      <a href="/sise/sise_index_day.nhn?code=KPI200&amp;page=546">
       맨뒤
       <img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
      </a>
     </td>
    </tr>
   </table>
   <!--- 페이지 네비게이션 끝--->
  </div>
  <!-- //일별시세 -->
  <script type="text/javascript">
   ;(function(){
        var eventType = "onpageshow" in window ? "pageshow" : "load";
        jindo.$Fn(function(){
            lcs_do();
        }).attach(window, eventType);
    })();
  </script>
 </body>
</html>
2019-04-04 286.15
2019-04-03 285.65
2019-04-02 281.72
2019-04-01 280.32
2019-03-29 276.48
2019-03-28 275.08
{datetime.date(2019, 4, 4): 21724.95, datetime.date(2019, 4, 3): 21713.21, datetime.date(2019, 4, 2): 21505.31, datetime.date(2019, 4, 1): 21509.03, datetime.date(2019, 3, 29): 21205.81, datetime.date(2019, 3, 28): 21033.76, datetime.date(2019, 3, 27): 21378.73, datetime.date(2019, 3, 26): 21428.39, datetime.date(2019, 3, 25): 20977.11, datetime.date(2019, 3, 22): 21627.34}

SPI@SPX S&P 500
NAS@NDX Nasdaq 100
NII@NI225 Nikkei 225

<h3> 만들어 둔 함수를 이용하여 KOSPI200과 S&P500 지수 추출 </h3>

In [ ]:
index_cd = 'KPI200'
historical_prices = dict()
kospi200 = historical_index_naver(index_cd, '2017-1-1','2017-12-31')

In [ ]:
index_cd = 'SPI@SPX'
historical_prices = dict()
sp500 = index_global(historical_prices, index_cd, '2017-1-1','2017-12-31') #대체 코드

In [ ]:
tmp = {'S&P500' : sp500, 'KOSPI200' : kospi200}

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(tmp)
df.head()

In [ ]:
df = df.fillna(method='fill')
if df.isnull().values.any():
    df = df.fillna(method='bfill')
df

<h2>matplotlib를 이용한 시각화</h2>

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.figure(figsize=(10,5))
plt.plot(df['S&P500'])
plt.plot(df['KOSPI200'])
plt.legend(loc=0)
plt.grid(True, color='0.7', linestyle=':', linewidth=1)

In [ ]:
df.iloc[0]

In [ ]:
df.loc[dt.date(2008, 1, 2)]

In [ ]:

plt.figure(figsize=(10, 5))
plt.plot(df['S&P500'] / df['S&P500'].loc[dt.date(2008, 1, 2)] * 100)
plt.plot(df['KOSPI200'] / df['KOSPI200'].loc[dt.date(2008, 1, 2)] * 100)
plt.legend(loc=0)
plt.grid(True, color='0.7', linestyle=':', linewidth=1)

In [ ]:
df_ratio_2016_now = df.loc[dt.date(2016, 1, 1):] / df.loc[dt.date(2016, 1, 4)] * 100
df_ratio_2016_now.head(3)

In [ ]:
plt.figure(figsize=(10, 5))
plt.plot(df_ratio_2016_now['S&P500'])
plt.plot(df_ratio_2016_now['KOSPI200'])
plt.legend(loc=0)
plt.grid(True, color='0.7', linestyle=':', linewidth=1)

In [ ]:
plt.figure(figsize=(7,7))
plt.scatter(df_ratio_2016_now['S&P500'], df_ratio_2016_now['KOSPI200'], marker='.')
plt.grid(True, color='0.7', linestyle=':', linewidth=1)
plt.xlabel('S&P500')
plt.ylabel('KOSPI200')

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression

x = df_ratio_2016_now['S&P500']
y = df_ratio_2016_now['KOSPI200']

# 1개 컬럼 np.array로 변환
independent_var = np.array(x).reshape(-1, 1)
dependent_var = np.array(y).reshape(-1, 1)

# Linear Regression
regr = LinearRegression()
regr.fit(independent_var, dependent_var)

result = {'Slope':regr.coef_[0,0], 'Intercept':regr.intercept_[0], 'R^2':regr.score(independent_var, dependent_var) }
result

In [ ]:
plt.figure(figsize=(7,7))
plt.scatter(independent_var, dependent_var, marker='.', color='skyblue')
plt.plot(independent_var, regr.predict(independent_var), color='r', linewidth=3)
plt.grid(True, color='0.7', linestyle=':', linewidth=1)
plt.xlabel('S&P500')
plt.ylabel('KOSPI200')